name: 'Entrance Gate'
version: '1.0'
description: 'Lets you add a confirmation box before allowing access to your website.'
url: 'https:/https://github.com/ipx-digital/entrance-gate'
developer: IPX
developer_url: 'https://ipx.org'
